# Generated by Django 4.2 on 2025-09-26 14:26

from django.db import migrations, models
import tenant_schemas.postgresql_backend.base


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("domain_url", models.CharField(max_length=128, unique=True)),
                ("schema_name", models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=200)),
                ("created_on", models.DateField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
